In [1]:
import numpy as np

### Exercício 1 - Considere o vetor [1, 2, 3, 4, 5], construa um novo vetor com três elementos 0 (zero) entre cada elemento do vetor.

**Resposta:**

In [2]:
arr_01 = np.array([1,2,3,4,5])
zeros = np.zeros(len(arr_01) + (len(arr_01) - 1) * (3), dtype=int)
zeros[::4] = arr_01
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

**Resposta:**

```
array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])
```

### Exercício 2 - Crie uma matriz quadrada de 8 X 8 e preencha com o padrão de tabuleiro de xadrez, utilizando 0 (zero) para casas brancas e 1 (um) para casas pretas.

**Resposta:**

In [3]:
arr_02 = np.tile( np.array([[0,1],[1,0]]), (4,4))
arr_02

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**Resposta:**

```
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])
```

### Exercício 3 - Dado um array de 2 dimensões, como trocar 2 linhas entre si?

**Resposta:**

#### array inicial:

In [4]:
arr_03  = np.arange(25).reshape((5,5))
arr_03

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### array com as linhas 0 e 1 trocadas entre si:

In [5]:
arr_03[[1,0]] = arr_03[[0,1]]
arr_03

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### array com as linhas 2 e 3 trocadas entre si:

In [6]:
arr03 = np.arange(25).reshape((5,5))
arr03[[3,2]] = arr03[[2,3]]
arr03

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 0 e 1 trocadas entre si:
```
array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])
```

### Exercício 4 - Dado um array de 2 dimensões, como trocar 2 colunas entre si?

**Resposta:**

#### array inicial:

In [7]:
arr_04 = np.array([(0,  1,  2,  3,  4), (5,  6,  7,  8,  9), (10, 11, 12, 13, 14),
                        (15, 16, 17, 18, 19), (20, 21, 22, 23, 24)], dtype=int)
arr_04

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### array com as colunas 2 e 3 trocadas entre si:

In [8]:
arr_copy = np.copy(arr_04[0:5, 2])
arr_04[0:5, 2] = arr_04[0:5, 3]
arr_04[0:5, 3] = arr_copy
arr_04

array([[ 0,  1,  3,  2,  4],
       [ 5,  6,  8,  7,  9],
       [10, 11, 13, 12, 14],
       [15, 16, 18, 17, 19],
       [20, 21, 23, 22, 24]])

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as colunas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  3,  2,  4],
       [ 5,  6,  8,  7,  9],
       [10, 11, 13, 12, 14],
       [15, 16, 18, 17, 19],
       [20, 21, 23, 22, 24]])
```

### Exercício 5 - Dado o array [1, 2, 3] criar o array [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

**Resposta:**

In [9]:
x , arr_05 = np.mgrid[0:4, 1:4]
arr_05

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

**Resposta:**

```
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])
``` 


### Exercício 6 - Dado o array [1, 2, 3] criar o array [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

**Resposta:**

In [10]:
arr_06 , x =  np.mgrid[1:4, 0:3]
arr_06

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

**Resposta:**

```
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])
```

### Exercício 7 - Dado o array [4, 95, 37, 64, 42, 19, 55, 38, 46, 83, 48, 67, 98, 21, 10, 88], obtenha todos os itens que estão entre 35 e 55.

**Resposta:**

In [11]:
arr_05 = np.array([4, 95, 37, 64, 42, 19, 55, 38, 46, 83, 48, 67, 98, 21, 10, 88])
arr_display = np.sort(arr_05)
arr_displayed = arr_display[((arr_display > 35) & (arr_display <= 55))]
arr_displayed

array([37, 38, 42, 46, 48, 55])

**Resposta:**

```
array([37, 42, 38, 46, 48, 55])
```

### Exercicio 8 - Considere um array com 100 elementos inteiros iniciando em 0. Dado um número randômico positivo e flutuante, descubra qual o elemento do array, mais próximo desse número.

**Resposta:**
#### array inicial de 100 elementos iniciado em 0:

In [12]:
arr_08 = np.arange(0, 100)
rand = np.random.uniform(0,100)
prox = np.where(arr_08 == round(rand,0))
arr_08

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### numero randomico, positivo e flutuante:

In [13]:
rand

82.83794617756584

#### elemento mais proximo no array:

In [14]:
prox

(array([83], dtype=int64),)

### Exercicio 9 - Dado um array, substitua todos os valores inferiores a 10 por 10 e todos os valores superiores a 30 por 30.

**Resposta:**
#### array inicial:

In [15]:
np.random.seed(100)
arr_09 = np.random.rand(30) * 50
arr_09

array([27.17024709, 13.91846925, 21.22587954, 42.23880662,  0.23594281,
        6.07845604, 33.53745424, 41.29263776,  6.83532948, 28.75466647,
       44.56609772, 10.46010611,  9.26641098,  5.41884452, 10.98487463,
       48.93118924, 40.58415745,  8.59705064, 40.81123744, 13.70368735,
       21.58520918, 47.00149098, 40.88246894, 16.80559751,  8.77052269,
       18.64160231,  0.28442537, 12.62131767, 39.78312542,  0.76274856])

#### array após substituições:

In [16]:
arr_09[arr_09 < 10] = 10
arr_09[arr_09 > 30] = 30
arr_09

array([27.17024709, 13.91846925, 21.22587954, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 28.75466647,
       30.        , 10.46010611, 10.        , 10.        , 10.98487463,
       30.        , 30.        , 10.        , 30.        , 13.70368735,
       21.58520918, 30.        , 30.        , 16.80559751, 10.        ,
       18.64160231, 10.        , 12.62131767, 30.        , 10.        ])

**Resposta**

array inicial:
```
array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])
```

array após as substituições:
```
array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])
```